export const SpellTechniqueCompatibility = {
  Enchanting: {
    "Quick Spell": false,
    "Spell Reflex": false,
    "Double Cast": false,
    "Double Pulse": false,
    "Carry Spell": false,
    "Spell Shift": false,
    "Counter Spell": false,
    "Spell Surge": false,
    "Junction Cast": false,
    "Spell Charge": false,
    "Focus Spell": false,
    "Hyper Spell": false,
    "Auto Cast": false,
    "Rivet Cast": false,
    "Spell Recovery": false,
    "Father Spell": false,
  },

  Deliverance: {
    "Quick Spell": false,
    "Spell Reflex": false,
    "Double Cast": false,
    "Double Pulse": false,
    "Carry Spell": false,
    "Spell Shift": false,
    "Counter Spell": false,
    "Spell Surge": false,
    "Junction Cast": false,
    "Spell Charge": false,
    "Focus Spell": false,
    "Hyper Spell": false,
    "Auto Cast": false,
    "Rivet Cast": false,
    "Spell Recovery": false,
    "Father Spell": false,
  },

  ElderMagic: {
    "Quick Spell": false,
    "Spell Reflex": false,
    "Double Cast": false,
    "Double Pulse": false,
    "Carry Spell": false,
    "Spell Shift": false,
    "Counter Spell": false,
    "Spell Surge": false,
    "Junction Cast": false,
    "Spell Charge": false,
    "Focus Spell": false,
    "Hyper Spell": false,
    "Auto Cast": false,
    "Rivet Cast": false,
    "Spell Recovery": false,
    "Father Spell": false,
  },

  Ghosting: {
    "Quick Spell": false,
    "Spell Reflex": false,
    "Double Cast": false,
    "Double Pulse": false,
    "Carry Spell": false,
    "Spell Shift": false,
    "Counter Spell": false,
    "Spell Surge": false,
    "Junction Cast": false,
    "Spell Charge": false,
    "Focus Spell": false,
    "Hyper Spell": false,
    "Auto Cast": false,
    "Rivet Cast": false,
    "Spell Recovery": false,
    "Father Spell": false,
  },

  HighMagic: {
    "Quick Spell": false,
    "Spell Reflex": false,
    "Double Cast": false,
    "Double Pulse": false,
    "Carry Spell": false,
    "Spell Shift": false,
    "Counter Spell": false,
    "Spell Surge": false,
    "Junction Cast": false,
    "Spell Charge": false,
    "Focus Spell": false,
    "Hyper Spell": false,
    "Auto Cast": false,
    "Rivet Cast": false,
    "Spell Recovery": false,
    "Father Spell": false,
  },

  Kinetics: {
    "Quick Spell": false,
    "Spell Reflex": false,
    "Double Cast": false,
    "Double Pulse": false,
    "Carry Spell": false,
    "Spell Shift": false,
    "Counter Spell": false,
    "Spell Surge": false,
    "Junction Cast": false,
    "Spell Charge": false,
    "Focus Spell": false,
    "Hyper Spell": false,
    "Auto Cast": false,
    "Rivet Cast": false,
    "Spell Recovery": false,
    "Father Spell": false,
  },

  Sealing: {
    "Quick Spell": false,
    "Spell Reflex": false,
    "Double Cast": false,
    "Double Pulse": false,
    "Carry Spell": false,
    "Spell Shift": false,
    "Counter Spell": false,
    "Spell Surge": false,
    "Junction Cast": false,
    "Spell Charge": false,
    "Focus Spell": false,
    "Hyper Spell": false,
    "Auto Cast": false,
    "Rivet Cast": false,
    "Spell Recovery": false,
    "Father Spell": false,
  },

  Sorcery: {
    "Quick Spell": false,
    "Spell Reflex": false,
    "Double Cast": false,
    "Double Pulse": false,
    "Carry Spell": false,
    "Spell Shift": false,
    "Counter Spell": false,
    "Spell Surge": false,
    "Junction Cast": false,
    "Spell Charge": false,
    "Focus Spell": false,
    "Hyper Spell": false,
    "Auto Cast": false,
    "Rivet Cast": false,
    "Spell Recovery": false,
    "Father Spell": false,
  },

  Transcendentalism: {
    "Quick Spell": false,
    "Spell Reflex": false,
    "Double Cast": false,
    "Double Pulse": false,
    "Carry Spell": false,
    "Spell Shift": false,
    "Counter Spell": false,
    "Spell Surge": false,
    "Junction Cast": false,
    "Spell Charge": false,
    "Focus Spell": false,
    "Hyper Spell": false,
    "Auto Cast": false,
    "Rivet Cast": false,
    "Spell Recovery": false,
    "Father Spell": false,
  },

  Alchemy: {
    "Quick Spell": false,
    "Spell Reflex": false,
    "Double Cast": false,
    "Double Pulse": false,
    "Carry Spell": false,
    "Spell Shift": false,
    "Counter Spell": false,
    "Spell Surge": false,
    "Junction Cast": false,
    "Spell Charge": false,
    "Focus Spell": false,
    "Hyper Spell": false,
    "Auto Cast": false,
    "Rivet Cast": false,
    "Spell Recovery": false,
    "Father Spell": false,
  },
} as const;
